Basics and components
Dmitrii98/angular-module-2 pull request #1
Opened 2023-02-13 19:46 UTC by Dmitrii98

2023-02-14 08:39 UTC, parabolabam requested changes
overall, LGTM 👍 
Could you pay slight attention to a couple of minor comments, please?

2023-02-14 08:39 UTC, parabolabam commented on src/app/shared/components/button/button.component.ts
> +@Input() text: string = ''
why not make it ng-content?

2023-02-14 08:39 UTC, parabolabam commented on src/app/app.component.html
> +           [open_modal_button_text]="'Open Modal'"
underscoreCase is usually avoided in angular applications and camelCase usually used

2023-02-14 08:39 UTC, parabolabam commented on src/app/app.component.html
> +           [okButtonText]="'Ok'"
mixing cases may be avoided to keep code consistent

2023-02-14 08:39 UTC, parabolabam commented on src/app/shared/shared.module.ts
> +export class SharedModule { }
it may grow so much and in some cases might affect bundle size if not reduced.
You may consider making each component a separate module that can be imported only on demand

2023-02-14 08:39 UTC, parabolabam commented on src/app/shared/components/course-card/course-card.component.html
> +<div class="course-card">
probably it should just card to stay in shared components, otherwise it's spe4cific implementation for course feature and should belong next to course component

2023-02-15 11:04 UTC, Dmitrii98 commented on src/app/shared/components/button/button.component.ts
> +@Input() text: string = ''
could you please elaborate on it or provide an example, please?

2023-02-15 11:19 UTC, Dmitrii98 commented on src/app/shared/components/course-card/course-card.component.html
> +<div class="course-card">
got your point, but let's imagine that `course-cart` is supposed to use somewhere else in the future :)

2023-02-15 11:22 UTC, Dmitrii98 commented on src/app/app.component.html
> +           [okButtonText]="'Ok'"
fixed

2023-02-15 11:22 UTC, Dmitrii98 commented on src/app/app.component.html
> +           [open_modal_button_text]="'Open Modal'"
fixed

2023-02-15 11:22 UTC, Dmitrii98 commented on src/app/shared/shared.module.ts
> +export class SharedModule { }
fixed

2023-02-15 11:36 UTC, parabolabam commented on src/app/shared/components/course-card/course-card.component.html
> +<div class="course-card">
If we want to reuse code from a particular part like course-card you'd probably import component from course-card module somewhere else. But honestly, it sounds like it's against my understanding of reusability. 

If we reuse course-card somewhere else it means it breaks borders of its domain modeling and might signal we do something wrong with system design.

But also bear in mind that since we ain't training system design, it's not critical to leave things as is for now

2023-02-15 11:36 UTC, parabolabam approved these changes

2023-02-15 11:39 UTC, merged